add vitest to readme and update cargo-nextest
trunk-io/docs pull request #350
Opened 2024-09-06 18:00 UTC by joshmarinacci

Also update some spelling.

2024-09-06 22:05 UTC, gewenyu99 requested changes

2024-09-06 22:05 UTC, gewenyu99 commented on code-quality/linters/supported/buildifier.md
> +- [Buildifier  site](https://github.com/rhysd/actionlint)
```suggestion
- [Buildifier site](https://github.com/rhysd/actionlint)
```

There's an extra space here.

2024-09-06 22:05 UTC, gewenyu99 commented on code-quality/linters/supported/clang-format.md
> -## Usage Notes
intentional or smthing wrong with script?

2024-09-06 22:05 UTC, gewenyu99 commented on code-quality/linters/supported/gofmt.md
> +Gofmt  will be auto-enabled if any *Go* files are present.
```suggestion
Gofmt will be auto-enabled if any *Go* files are present.
```

extra space

2024-09-06 22:05 UTC, gewenyu99 commented on code-quality/linters/supported/tflint.md
> +# TFLint
Extra space

2024-09-06 22:05 UTC, gewenyu99 commented on flaky-tests/frameworks/vitest.md
> +Vitest is a testing framework for Javascript.
```suggestion
Vitest is a testing framework for JavaScript.
```

2024-09-06 22:05 UTC, gewenyu99 commented on flaky-tests/frameworks/vitest.md
> +
```suggestion
We should really get rid of these trailing spaces from the script 📦 
```

2024-09-09 18:55 UTC, joshmarinacci commented on code-quality/linters/supported/buildifier.md
> +- [Buildifier  site](https://github.com/rhysd/actionlint)
extra space in the Dato entry. Fixed.

2024-09-09 20:10 UTC, merged